// Expanded product data with specifications and detailed information
export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  status: "in-stock" | "out-of-stock" | "new";
  category: string;
  brand: string;
  rating: number;
  reviews: number;
  description: string;
  specs: Record<string, string>;
  compatibility?: string[];
  tags: string[];
}

export const products: Product[] = [
  {
    id: "1",
    name: "They-re Radio P77",
    price: 179,
    image: "https://framerusercontent.com/images/C67lEKfFEQ9Ao4GMknVpRjdQSPo.png",
    status: "in-stock",
    category: "Radio",
    brand: "They-re",
    rating: 4.5,
    reviews: 128,
    description: "Premium vintage-style radio with modern connectivity. Perfect for retro enthusiasts.",
    specs: {
      "Frequency Range": "FM/AM",
      "Power": "AC/Battery",
      "Dimensions": "12 x 8 x 4 inches",
      "Weight": "2.5 lbs",
      "Connectivity": "Bluetooth, 3.5mm Jack",
    },
    tags: ["vintage", "radio", "bluetooth", "retro"],
  },
  {
    id: "2",
    name: "Radion T28",
    price: 129,
    image: "https://framerusercontent.com/images/J2eFqmrs2I831EXbJfBQyNaMI.png",
    status: "in-stock",
    category: "Radio",
    brand: "Radion",
    rating: 4.2,
    reviews: 95,
    description: "Compact portable radio with excellent sound quality.",
    specs: {
      "Frequency Range": "FM/AM",
      "Power": "Battery/AC",
      "Dimensions": "6 x 4 x 2 inches",
      "Weight": "0.8 lbs",
      "Connectivity": "3.5mm Jack",
    },
    tags: ["portable", "radio", "compact"],
  },
  {
    id: "3",
    name: "Clock Orange O2",
    price: 399,
    image: "https://framerusercontent.com/images/dlSQBjwpKaHj9r2I3UFrWjaddak.png",
    status: "out-of-stock",
    category: "Clock",
    brand: "Orange",
    rating: 4.8,
    reviews: 234,
    description: "Analog clock with precision engineering and minimalist design.",
    specs: {
      "Type": "Analog",
      "Diameter": "10 inches",
      "Material": "Stainless Steel",
      "Accuracy": "±5 seconds/month",
      "Power": "Battery (AA)",
    },
    tags: ["clock", "analog", "minimalist", "design"],
  },
  {
    id: "4",
    name: "Radion Y-01",
    price: 199,
    image: "https://framerusercontent.com/images/mTzSE6KF0SZuuB0yuiIuLJScuYo.png",
    status: "in-stock",
    category: "Radio",
    brand: "Radion",
    rating: 4.6,
    reviews: 156,
    description: "Advanced radio with digital display and preset stations.",
    specs: {
      "Frequency Range": "FM/AM/SW",
      "Display": "Digital LCD",
      "Power": "AC/Battery",
      "Presets": "20 Stations",
      "Connectivity": "Bluetooth, USB",
    },
    tags: ["radio", "digital", "advanced"],
  },
  {
    id: "5",
    name: "Proto T 52",
    price: 99,
    image: "https://framerusercontent.com/images/iqlO85MtzwaDJDynNJM1ZwWvNys.png",
    status: "out-of-stock",
    category: "Gaming",
    brand: "Proto",
    rating: 4.3,
    reviews: 87,
    description: "Handheld gaming device with retro charm and modern performance.",
    specs: {
      "Screen": "3.5 inch LCD",
      "Resolution": "320x240",
      "Games": "500+ Built-in",
      "Battery": "10 hours",
      "Connectivity": "Link Cable",
    },
    tags: ["gaming", "handheld", "retro"],
  },
  {
    id: "6",
    name: "Radiot P52",
    price: 299,
    image: "https://framerusercontent.com/images/Bh5yiJhSRHnGMNKs3ITKN7R1rq4.png",
    status: "in-stock",
    category: "Radio",
    brand: "Radiot",
    rating: 4.7,
    reviews: 203,
    description: "Professional-grade radio with exceptional audio quality.",
    specs: {
      "Frequency Range": "FM/AM/SW/LW",
      "Power Output": "10W",
      "Dimensions": "14 x 10 x 5 inches",
      "Weight": "3.2 lbs",
      "Connectivity": "Bluetooth, USB, AUX",
    },
    tags: ["professional", "radio", "audio"],
  },
  {
    id: "7",
    name: "AX-34 Deck",
    price: 159,
    image: "https://framerusercontent.com/images/UzlqqmSBYDe3mG46DVCNbucgg.png",
    status: "in-stock",
    category: "Audio",
    brand: "AX",
    rating: 4.4,
    reviews: 112,
    description: "Vintage cassette deck with modern reliability.",
    specs: {
      "Type": "Cassette Deck",
      "Tracks": "2-Track Stereo",
      "Speed": "1 7/8 ips",
      "Wow & Flutter": "<0.15%",
      "Connectivity": "RCA, 3.5mm",
    },
    tags: ["audio", "cassette", "vintage"],
  },
  {
    id: "8",
    name: "Pocket Play X-RP",
    price: 279,
    image: "https://framerusercontent.com/images/amf7AUxXbx8JQqjTSxSa86sHI1Q.png",
    status: "in-stock",
    category: "Gaming",
    brand: "Pocket",
    rating: 4.6,
    reviews: 189,
    description: "Premium handheld gaming console with crystal-clear display.",
    specs: {
      "Screen": "4.3 inch OLED",
      "Resolution": "480x272",
      "Games": "1000+ Compatible",
      "Battery": "12 hours",
      "Connectivity": "WiFi, Bluetooth",
    },
    tags: ["gaming", "handheld", "premium"],
  },
  {
    id: "9",
    name: "SP-4 Radio",
    price: 149,
    image: "https://framerusercontent.com/images/sf2RXVteaVIKZ4CMMDuy5OxJgFw.png",
    status: "in-stock",
    category: "Radio",
    brand: "SP",
    rating: 4.5,
    reviews: 134,
    description: "Compact speaker-radio combo for on-the-go listening.",
    specs: {
      "Type": "Speaker + Radio",
      "Power": "5W Speaker",
      "Frequency": "FM/AM",
      "Connectivity": "Bluetooth, USB",
      "Battery": "8 hours",
    },
    tags: ["radio", "speaker", "portable"],
  },
  {
    id: "10",
    name: "SonicWave X1",
    price: 199,
    image: "https://framerusercontent.com/images/9IuqsvqmUCrbEJwmzoNFxDgt5U.png",
    status: "out-of-stock",
    category: "Audio",
    brand: "SonicWave",
    rating: 4.7,
    reviews: 267,
    description: "High-fidelity wireless speaker with room-filling sound.",
    specs: {
      "Power": "20W",
      "Frequency": "20Hz - 20kHz",
      "Connectivity": "Bluetooth 5.0, WiFi",
      "Battery": "15 hours",
      "Waterproof": "IPX7",
    },
    tags: ["audio", "speaker", "wireless", "hifi"],
  },
  {
    id: "11",
    name: "Calc 9000",
    price: 79,
    image: "https://framerusercontent.com/images/NjETYEJv2gTFoNCccRUMElCkPg.png",
    status: "in-stock",
    category: "Calculator",
    brand: "Calc",
    rating: 4.1,
    reviews: 56,
    description: "Scientific calculator with large display and solar power.",
    specs: {
      "Type": "Scientific",
      "Functions": "240+",
      "Display": "2-line LCD",
      "Power": "Solar + Battery",
      "Dimensions": "5 x 3 x 0.5 inches",
    },
    tags: ["calculator", "scientific", "solar"],
  },
  {
    id: "12",
    name: "NeoChrono Console",
    price: 399,
    image: "https://framerusercontent.com/images/FVlTCVAMDL4uYxEnpzFQyoZrNZo.png",
    status: "out-of-stock",
    category: "Gaming",
    brand: "NeoChrono",
    rating: 4.9,
    reviews: 412,
    description: "Retro gaming console with modern features and extensive library.",
    specs: {
      "Games": "500+ Built-in",
      "Resolution": "720p",
      "Connectivity": "HDMI, USB",
      "Controllers": "2 Wireless",
      "Storage": "32GB Internal",
    },
    tags: ["gaming", "console", "retro", "premium"],
  },
  {
    id: "13",
    name: "Recordio ZT 1",
    price: 99,
    image: "https://framerusercontent.com/images/0s6mPyGAVm85FLM7Z7vvtGQYEZ4.png",
    status: "in-stock",
    category: "Audio",
    brand: "Recordio",
    rating: 4.2,
    reviews: 78,
    description: "Portable digital recorder with high-quality audio capture.",
    specs: {
      "Format": "WAV/MP3",
      "Bitrate": "320kbps",
      "Storage": "8GB",
      "Battery": "6 hours",
      "Microphone": "Built-in Stereo",
    },
    tags: ["audio", "recorder", "portable"],
  },
  {
    id: "14",
    name: "Gamebrot 0XR",
    price: 189,
    image: "https://framerusercontent.com/images/7gTyrPv3vkoowZ8uAS0PhZ7qfR8.png",
    status: "out-of-stock",
    category: "Gaming",
    brand: "Gamebrot",
    rating: 4.4,
    reviews: 145,
    description: "Advanced gaming controller with haptic feedback.",
    specs: {
      "Connectivity": "Wireless 2.4GHz",
      "Battery": "20 hours",
      "Buttons": "16 Programmable",
      "Vibration": "Dual Haptic",
      "Compatibility": "PC, Console",
    },
    tags: ["gaming", "controller", "wireless"],
  },
  {
    id: "15",
    name: "Headset x28",
    price: 189,
    image: "https://framerusercontent.com/images/Q3GZoob7o00Ph3EvrwhWAqbfPI.png",
    status: "in-stock",
    category: "Audio",
    brand: "Headset",
    rating: 4.6,
    reviews: 198,
    description: "Premium wireless headset with noise cancellation.",
    specs: {
      "Type": "Over-ear",
      "Connectivity": "Bluetooth 5.0",
      "Noise Cancellation": "Active",
      "Battery": "30 hours",
      "Microphone": "Built-in",
    },
    tags: ["audio", "headset", "wireless", "noise-cancelling"],
  },
  {
    id: "16",
    name: "Peeuriva 24-T4",
    price: 189,
    image: "https://framerusercontent.com/images/jj10qxfx4o42XIpRi5mhD0G02M.png",
    status: "out-of-stock",
    category: "Speaker",
    brand: "Peeuriva",
    rating: 4.3,
    reviews: 109,
    description: "Portable Bluetooth speaker with 360-degree sound.",
    specs: {
      "Power": "15W",
      "Connectivity": "Bluetooth 4.2",
      "Battery": "12 hours",
      "Waterproof": "IPX5",
      "Sound": "360-degree",
    },
    tags: ["speaker", "portable", "bluetooth"],
  },
];

export const categories = [
  { id: "all", name: "All Products", count: products.length },
  { id: "radio", name: "Radio", count: products.filter(p => p.category === "Radio").length },
  { id: "audio", name: "Audio", count: products.filter(p => p.category === "Audio").length },
  { id: "gaming", name: "Gaming", count: products.filter(p => p.category === "Gaming").length },
  { id: "clock", name: "Clock", count: products.filter(p => p.category === "Clock").length },
  { id: "calculator", name: "Calculator", count: products.filter(p => p.category === "Calculator").length },
  { id: "speaker", name: "Speaker", count: products.filter(p => p.category === "Speaker").length },
];

export const brands = Array.from(new Set(products.map(p => p.brand))).sort();

export const priceRanges = [
  { id: "0-100", label: "Under $100", min: 0, max: 100 },
  { id: "100-200", label: "$100 - $200", min: 100, max: 200 },
  { id: "200-300", label: "$200 - $300", min: 200, max: 300 },
  { id: "300+", label: "$300+", min: 300, max: Infinity },
];
